### ISSUE TITLE
viper.ReadInConfig() not working on ubuntu

### ISSUE THREAD

**Issue by shahzadthathal** [Fikri1234/JWT_REST_Gin_MySQL#2]
I don't have windows I'm using Ubuntu and this command not works on Ubuntu: 
`5. Open cmd and type setx APP_ENVIRONMENT STAGING for default environment`

Solution is open main.go and inside init func add this line and run `go run main.go
`
```
func init() {

	os.Setenv("APP_ENVIRONMENT", "STAGING")
```

**Comment by Fikri1234** [comment]
sure,,you also can type this command in your ubuntu APP_ENVIRONMENT=STAGING

**Comment by Fikri1234** [comment]
you can type this command in your ubuntu APP_ENVIRONMENT=STAGING
